name: "✨ Feature Request"
description: Suggest an idea to improve Godot Launcher
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to improve Godot Launcher? Awesome — fill this out to help us understand and prioritize it.

  - type: textarea
    id: problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: Describe the problem or frustration that this feature would solve.
      placeholder: "Ex. I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: What would you like to see added or improved?
      placeholder: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: Have you thought of any other ways this could be solved or similar tools that do it differently?
      placeholder: "I currently do X manually... / I've seen Y do it like this..."
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: "Feature area"
      description: What part of the launcher does this affect?
      options:
        - Project management
        - Godot version handling
        - Editor settings
        - UI/UX or visuals
        - System tray or background behavior
        - Other (please explain above)
      multiple: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context or mockups"
      description: Include screenshots, sketches, or any extra explanation that could help clarify your idea.
      placeholder: "Images, references, or use cases..."
